### ISSUE TITLE
Not Saving Attributes

### ISSUE THREAD

**Issue by IanVS** [sane/sails-hook-jsonapi#1]
So far, I've focused on sending a response as jsonapi.  The other side of the coin is accepting requests in jsonapi and saving attributes correctly.  Thus far, this does not happen.

**Comment by curtisgr** [comment]
Where are you with this?  I think this is a great project.

**Comment by IanVS** [comment]
Hi, thanks for the interest.  So far I've not had a chance to really figure this out.  I have a feeling I'll need to override blueprints, but I'm trying to avoid that.  If you have any thoughts (or PRs!) please feel free to send them this way. :smile_cat:

**Comment by IanVS** [comment]
There is an [RFC](https://github.com/SeyZ/jsonapi-serializer/issues/42) in jsonapi-serializer to add deserialization, which would help this effort greatly.

**Comment by sescobb27** [comment]
I made a PR https://github.com/SeyZ/jsonapi-serializer/pull/43 for that RFC, if you would like to try it. thats what we are using in our servers rigth now

**Comment by Kuzirashi** [comment]
Hey, will this project be continued?

**Comment by IanVS** [comment]
At this time I am no longer using Sails or Ember, so I am unlikely to continue working on it any time soon, unfortunately.   I'd be happy to turn it over to anyone else who's interested in carrying the torch.

**Comment by dadleyy** [comment]
@IanVS out of curiosity what have you moved onto (for your api)?

**Comment by IanVS** [comment]
I've joined a startup using PHP on the backend (but still emitting json-api).

**Comment by dadleyy** [comment]
interesting. thanks!

**Comment by jelhan** [comment]
https://github.com/SeyZ/jsonapi-serializer [supports deserialization](https://github.com/SeyZ/jsonapi-serializer#deserialization) since 2.1.0. It wasn't documented before 3.0.0.

**Comment by IanVS** [comment]
@jelhan, very cool.  Want to take a shot at a PR?

**Comment by jelhan** [comment]
@IanVS I'm not quite sure yet. Currently I'm investigating what work is necessary to get this working with Ember.js. Just sharing results.

**Comment by jelhan** [comment]
I started work on a PR to support creating, updating and deleting resources.

**Comment by jelhan** [comment]
Creating and deleting resources is implemented. Have started work on update here: https://github.com/jelhan/sails-hook-jsonapi/tree/update

**Comment by jelhan** [comment]
Updating has just been merged. Closing this one for now.
