### ISSUE TITLE
npm package not updated

### ISSUE THREAD

**Issue by oiramalli** [sane/sails-hook-jsonapi#14]
If you try to install via npm, you don't get the latest version, you have to update the dependencies yourself.

**Comment by IanVS** [comment]
Thanks for the heads-up, I'll get a new version published.

**Comment by IanVS** [comment]
@jelhan, is master releasable as a new `0.0.4` version currently?

**Comment by jelhan** [comment]
I think so. update support is hanging cause of https://github.com/SeyZ/jsonapi-serializer/pull/89. Could be part of `0.0.5` therefore.

**Comment by IanVS** [comment]
Unfortunately it looks like jsonapi-serializer has not had any activity for two months.  I hope it is not abandoned.

**Comment by jelhan** [comment]
@IanVS Feel free to push another patch release.

**Comment by IanVS** [comment]
If you'd like to bump the npm version and create a git tag with a few notes about what's changed, I'll be more than happy to publish it to npm.

**Comment by jelhan** [comment]
@IanVS just pushed 0.0.4 to github and added a summarized changelog as release note.

**Comment by IanVS** [comment]
`0.0.4` has been published.
