### ISSUE TITLE
travis tests aren't running

### ISSUE THREAD

**Issue by jelhan** [sane/sails-hook-jsonapi#16]
> dummy@0.0.0 test /home/travis/build/sane/sails-hook-jsonapi/tests/dummy
> echo 'Error: no test specified'

Seems like nobody noticed. It's the case since [Build #1](https://travis-ci.org/sane/sails-hook-jsonapi/jobs/111119847#L1638-L1639).

**Comment by IanVS** [comment]
Hah!  Yeah that'll do it.
